spring:
  datasource:
    url:
    username:
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

jwt:
  header: Authorization
  secret:
  token-validity-in-seconds: 86400

cloud:
  aws:
    stack:
      auto: false
    region:
      static:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
